In [7]:
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv("../data/raw/kobe_career_stats.csv")

df.head()

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,977,1996-97,0,1610612747,LAL,18.0,71,6,1102,176,...,0.819,47,85,132,91,49,23,112,102,539
1,977,1997-98,0,1610612747,LAL,19.0,79,1,2056,391,...,0.794,79,163,242,199,74,40,157,180,1220
2,977,1998-99,0,1610612747,LAL,20.0,50,50,1896,362,...,0.839,53,211,264,190,72,50,157,153,996
3,977,1999-00,0,1610612747,LAL,21.0,66,62,2524,554,...,0.821,108,308,416,323,106,62,182,220,1485
4,977,2000-01,0,1610612747,LAL,22.0,68,68,2783,701,...,0.853,104,295,399,338,114,43,220,222,1938

In [9]:
df.shape

(20, 27)

In [10]:
df.columns.tolist()

['PLAYER_ID',
 'SEASON_ID',
 'LEAGUE_ID',
 'TEAM_ID',
 'TEAM_ABBREVIATION',
 'PLAYER_AGE',
 'GP',
 'GS',
 'MIN',
 'FGM',
 'FGA',
 'FG_PCT',
 'FG3M',
 'FG3A',
 'FG3_PCT',
 'FTM',
 'FTA',
 'FT_PCT',
 'OREB',
 'DREB',
 'REB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PTS']

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PLAYER_ID          20 non-null     int64
 1   SEASON_ID          20 non-null     str
 2   LEAGUE_ID          20 non-null     int64
 3   TEAM_ID            20 non-null     int64
 4   TEAM_ABBREVIATION  20 non-null     str
 5   PLAYER_AGE         20 non-null     float64
 6   GP                 20 non-null     int64
 7   GS                 20 non-null     int64
 8   MIN                20 non-null     int64
 9   FGM                20 non-null     int64
 10  FGA                20 non-null     int64
 11  FG_PCT             20 non-null     float64
 12  FG3M               20 non-null     int64
 13  FG3A               20 non-null     int64
 14  FG3_PCT            20 non-null     float64
 15  FTM                20 non-null     int64
 16  FTA                20 non-null     int64
 17  FT_PCT             20 non-null     float64
 18  OREB               20 non-null     int64
 19  DREB               20 non-null     int64
 20  REB                20 non-null     int64
 21  AST                20 non-null     int64
 22  STL                20 non-null     int64
 23  BLK                20 non-null     int64
 24  TOV                20 non-null     int64
 25  PF                 20 non-null     int64
 26  PTS                20 non-null     int64
dtypes: float64(4), int64(21), str(2)
memory usage: 4.3 KB

In [12]:
df["MPG"] = df["MIN"] / df["GP"]

df["PPG"] = df["PTS"] / df["GP"]
df["APG"] = df["AST"] / df["GP"]
df["RPG"] = df["REB"] / df["GP"]
df["SPG"] = df["STL"] / df["GP"]
df["BPG"] = df["BLK"] / df["GP"]
df["TOPG"] = df["TOV"] / df["GP"]

df["TS_PCT"] = df["PTS"] / (
    2 * (df["FGA"] + 0.44 * df["FTA"])
)

df["EFG_PCT"] = (
    df["FGM"] + 0.5 * df["FG3M"]
) / df["FGA"]

df["THREE_PA_RATE"] = df["FG3A"] / df["FGA"]

df["FTA_RATE"] = df["FTA"] / df["FGA"]

In [13]:
career_view = df[
    [
        "SEASON_ID",
        "PLAYER_AGE",
        "GP",
        "MPG",
        "PPG",
        "APG",
        "RPG",
        "SPG",
        "BPG",
        "FG_PCT",
        "FG3_PCT",
        "FT_PCT",
        "TS_PCT",
        "EFG_PCT",
        "THREE_PA_RATE",
        "FTA_RATE"
    ]
].copy()

career_view.round(3)

,SEASON_ID,PLAYER_AGE,GP,MPG,PPG,APG,RPG,SPG,BPG,FG_PCT,FG3_PCT,FT_PCT,TS_PCT,EFG_PCT,THREE_PA_RATE,FTA_RATE
0,1996-97,18.0,71,15.521,7.592,1.282,1.859,0.690,0.324,0.417,0.375,0.819,0.544,0.477,0.322,0.393
1,1997-98,19.0,79,26.025,15.443,2.519,3.063,0.937,0.506,0.428,0.341,0.794,0.548,0.469,0.241,0.501
2,1998-99,20.0,50,37.920,19.920,3.800,5.280,1.440,1.000,0.465,0.267,0.839,0.549,0.482,0.130,0.375
3,1999-00,21.0,66,38.242,22.500,4.894,6.303,1.606,0.939,0.468,0.319,0.821,0.546,0.488,0.122,0.341
4,2000-01,22.0,68,40.926,28.500,4.971,5.868,1.676,0.632,0.464,0.305,0.853,0.552,0.484,0.132,0.369
5,2001-02,23.0,80,38.312,25.238,5.475,5.512,1.475,0.438,0.469,0.250,0.829,0.544,0.479,0.083,0.369
6,2002-03,24.0,82,41.476,30.012,5.866,6.878,2.207,0.817,0.451,0.383,0.843,0.550,0.483,0.168,0.371
7,2003-04,25.0,65,37.723,23.954,5.077,5.523,1.723,0.431,0.438,0.327,0.852,0.551,0.468,0.184,0.452
8,2004-05,26.0,66,40.742,27.561,6.030,5.939,1.303,0.803,0.433,0.339,0.816,0.563,0.482,0.292,0.502
9,2005-06,27.0,80,40.962,35.400,4.500,5.312,1.838,0.375,0.450,0.347,0.850,0.559,0.491,0.238,0.377
10,2006-07,28.0,77,40.779,31.558,5.364,5.701,1.442,0.468,0.463,0.344,0.868,0.580,0.502,0.227,0.437
11,2007-08,29.0,82,38.927,28.329,5.378,6.305,1.841,0.488,0.459,0.361,0.840,0.576,0.503,0.246,0.439
12,2008-09,30.0,82,36.098,26.841,4.866,5.232,1.463,0.451,0.467,0.351,0.856,0.561,0.502,0.196,0.329
13,2009-10,31.0,73,38.836,26.986,5.000,5.356,1.548,0.274,0.456,0.329,0.811,0.545,0.488,0.192,0.345
14,2010-11,32.0,82,33.890,25.341,4.732,5.110,1.207,0.146,0.451,0.323,0.828,0.548,0.487,0.217,0.356
15,2011-12,33.0,58,38.483,27.862,4.552,5.397,1.190,0.310,0.430,0.303,0.845,0.527,0.462,0.215,0.338
16,2012-13,34.0,78,38.628,27.346,6.013,5.551,1.359,0.321,0.463,0.324,0.839,0.570,0.504,0.255,0.392
17,2013-14,35.0,6,29.500,13.833,6.333,4.333,1.167,0.167,0.425,0.188,0.857,0.505,0.445,0.219,0.288
18,2014-15,36.0,35,34.486,22.343,5.629,5.686,1.343,0.200,0.373,0.293,0.813,0.477,0.411,0.258,0.338
19,2015-16,37.0,66,28.227,17.591,2.788,3.742,0.939,0.197,0.358,0.285,0.826,0.469,0.417,0.420,0.252

In [14]:
career_view = df[
    [
        "SEASON_ID",
        "PLAYER_AGE",
        "GP",
        "MPG",
        "PPG",
        "APG",
        "RPG",
        "SPG",
        "BPG",
        "FG_PCT",
        "FG3_PCT",
        "FT_PCT",
        "TS_PCT",
        "EFG_PCT",
        "THREE_PA_RATE",
        "FTA_RATE"
    ]
].copy()

career_view.round(3)

,SEASON_ID,PLAYER_AGE,GP,MPG,PPG,APG,RPG,SPG,BPG,FG_PCT,FG3_PCT,FT_PCT,TS_PCT,EFG_PCT,THREE_PA_RATE,FTA_RATE
0,1996-97,18.0,71,15.521,7.592,1.282,1.859,0.690,0.324,0.417,0.375,0.819,0.544,0.477,0.322,0.393
1,1997-98,19.0,79,26.025,15.443,2.519,3.063,0.937,0.506,0.428,0.341,0.794,0.548,0.469,0.241,0.501
2,1998-99,20.0,50,37.920,19.920,3.800,5.280,1.440,1.000,0.465,0.267,0.839,0.549,0.482,0.130,0.375
3,1999-00,21.0,66,38.242,22.500,4.894,6.303,1.606,0.939,0.468,0.319,0.821,0.546,0.488,0.122,0.341
4,2000-01,22.0,68,40.926,28.500,4.971,5.868,1.676,0.632,0.464,0.305,0.853,0.552,0.484,0.132,0.369
5,2001-02,23.0,80,38.312,25.238,5.475,5.512,1.475,0.438,0.469,0.250,0.829,0.544,0.479,0.083,0.369
6,2002-03,24.0,82,41.476,30.012,5.866,6.878,2.207,0.817,0.451,0.383,0.843,0.550,0.483,0.168,0.371
7,2003-04,25.0,65,37.723,23.954,5.077,5.523,1.723,0.431,0.438,0.327,0.852,0.551,0.468,0.184,0.452
8,2004-05,26.0,66,40.742,27.561,6.030,5.939,1.303,0.803,0.433,0.339,0.816,0.563,0.482,0.292,0.502
9,2005-06,27.0,80,40.962,35.400,4.500,5.312,1.838,0.375,0.450,0.347,0.850,0.559,0.491,0.238,0.377
10,2006-07,28.0,77,40.779,31.558,5.364,5.701,1.442,0.468,0.463,0.344,0.868,0.580,0.502,0.227,0.437
11,2007-08,29.0,82,38.927,28.329,5.378,6.305,1.841,0.488,0.459,0.361,0.840,0.576,0.503,0.246,0.439
12,2008-09,30.0,82,36.098,26.841,4.866,5.232,1.463,0.451,0.467,0.351,0.856,0.561,0.502,0.196,0.329
13,2009-10,31.0,73,38.836,26.986,5.000,5.356,1.548,0.274,0.456,0.329,0.811,0.545,0.488,0.192,0.345
14,2010-11,32.0,82,33.890,25.341,4.732,5.110,1.207,0.146,0.451,0.323,0.828,0.548,0.487,0.217,0.356
15,2011-12,33.0,58,38.483,27.862,4.552,5.397,1.190,0.310,0.430,0.303,0.845,0.527,0.462,0.215,0.338
16,2012-13,34.0,78,38.628,27.346,6.013,5.551,1.359,0.321,0.463,0.324,0.839,0.570,0.504,0.255,0.392
17,2013-14,35.0,6,29.500,13.833,6.333,4.333,1.167,0.167,0.425,0.188,0.857,0.505,0.445,0.219,0.288
18,2014-15,36.0,35,34.486,22.343,5.629,5.686,1.343,0.200,0.373,0.293,0.813,0.477,0.411,0.258,0.338
19,2015-16,37.0,66,28.227,17.591,2.788,3.742,0.939,0.197,0.358,0.285,0.826,0.469,0.417,0.420,0.252

In [15]:
# Kobe career reference values
total_gp = df["GP"].sum()

kobe_reference = {
    "MPG": df["MIN"].sum() / total_gp,
    "PPG": df["PTS"].sum() / total_gp,
    "APG": df["AST"].sum() / total_gp,
    "RPG": df["REB"].sum() / total_gp,
    "SPG": df["STL"].sum() / total_gp,
    "BPG": df["BLK"].sum() / total_gp,
    "TOPG": df["TOV"].sum() / total_gp,

    "FG_PCT": df["FGM"].sum() / df["FGA"].sum(),
    "FG3_PCT": df["FG3M"].sum() / df["FG3A"].sum(),
    "FT_PCT": df["FTM"].sum() / df["FTA"].sum(),

    "TS_PCT": df["PTS"].sum() / (
        2 * (df["FGA"].sum() + 0.44 * df["FTA"].sum())
    ),

    "EFG_PCT": (
        df["FGM"].sum() + 0.5 * df["FG3M"].sum()
    ) / df["FGA"].sum(),

    "THREE_PA_RATE": df["FG3A"].sum() / df["FGA"].sum(),
    "FTA_RATE": df["FTA"].sum() / df["FGA"].sum()
}

kobe_reference

{'MPG': np.float64(36.13893016344725),
 'PPG': np.float64(24.994799405646358),
 'APG': np.float64(4.684992570579495),
 'RPG': np.float64(5.235512630014859),
 'SPG': np.float64(1.4442793462109955),
 'BPG': np.float64(0.475482912332838),
 'TOPG': np.float64(2.9791976225854384),
 'FG_PCT': np.float64(0.44729007633587786),
 'FG3_PCT': np.float64(0.3294266137756942),
 'FT_PCT': np.float64(0.8368794326241135),
 'TS_PCT': np.float64(0.5496352864448891),
 'EFG_PCT': np.float64(0.48215648854961835),
 'THREE_PA_RATE': np.float64(0.2116793893129771),
 'FTA_RATE': np.float64(0.38209923664122136)}

In [16]:
def similarity_score(reference, candidate):
    if reference == 0:
        return 100 if candidate == 0 else 0

    difference = abs(candidate - reference)
    percentage_difference = difference / abs(reference)

    return max(0, 100 * (1 - percentage_difference))

In [17]:
similarity_score(7.67, 7.37)

96.08865710560626

In [18]:
candidate_names = [
    "Shai Gilgeous-Alexander",
    "Luka Doncic",
    "Anthony Edwards",
    "Devin Booker",
    "Jalen Brunson",
    "Jaylen Brown",
    "Jayson Tatum",
    "Kevin Durant",
    "Kawhi Leonard",
    "Jimmy Butler",
    "LeBron James",
    "Donovan Mitchell",
    "Ja Morant",
    "De'Aaron Fox",
    "Tyrese Maxey",
    "Cade Cunningham",
    "Trae Young",
    "Jamal Murray",
    "Stephen Curry",
    "Nikola Jokic",
    "LaMelo Ball",
    "Darius Garland",
    "Jalen Williams",
    "Desmond Bane",
    "Brandon Ingram",
    "Mikal Bridges",
    "OG Anunoby",
    "RJ Barrett",
    "Scottie Barnes",
    "Paolo Banchero",
    "Franz Wagner",
    "Jalen Johnson",
    "Julius Randle",
    "Deni Avdija",
    "Brandon Miller",
    "Cam Thomas",
    "Anfernee Simons",
    "Jordan Poole",
    "Tyler Herro",
    "Dejounte Murray",
    "CJ McCollum",
    "DeMar DeRozan",
    "Michael Porter Jr.",
    "Zach LaVine",
    "Norman Powell",
    "Bradley Beal",
    "Khris Middleton",
    "Andrew Wiggins",
    "Aaron Gordon",
    "Jerami Grant",
    "Miles Bridges",
    "Trey Murphy III",
    "Jaden McDaniels",
    "Austin Reaves",
    "Collin Sexton",
    "Jordan Clarkson",
    "Buddy Hield",
    "Klay Thompson",
    "Harrison Barnes",
    "Zion Williamson",
    "Pascal Siakam",
    "Lauri Markkanen",
    "Chet Holmgren",
    "Bam Adebayo",
    "Paul George",
    "Jrue Holiday",
    "Jalen Green",
    "Amen Thompson",
    "Devin Vassell",
    "Victor Wembanyama"
]

len(candidate_names)

70

In [19]:
from nba_api.stats.static import players

candidate_records = []

for name in candidate_names:
    matches = players.find_players_by_full_name(name)

    if matches:
        player = matches[0]

        candidate_records.append({
            "PLAYER_ID": player["id"],
            "PLAYER_NAME": player["full_name"]
        })
    else:
        print("NOT FOUND:", name)

candidate_pool = pd.DataFrame(candidate_records)

candidate_pool

    PLAYER_ID              PLAYER_NAME
0     1628983  Shai Gilgeous-Alexander
1     1629029              Luka Dončić
2     1630162          Anthony Edwards
3     1626164             Devin Booker
4     1628973            Jalen Brunson
..        ...                      ...
65     201950             Jrue Holiday
66    1630224              Jalen Green
67    1641708            Amen Thompson
68    1630170            Devin Vassell
69    1641705        Victor Wembanyama

[70 rows x 2 columns]

In [20]:
candidate_pool.shape

(70, 2)

In [21]:
from pathlib import Path

output_path = Path("../data/manual/candidate_pool.csv")
output_path.parent.mkdir(parents=True, exist_ok=True)

candidate_pool.to_csv(output_path, index=False)

print(f"Saved candidate pool to: {output_path}")

Saved candidate pool to: ..\data\manual\candidate_pool.csv

In [22]:
from nba_api.stats.endpoints import leaguedashplayerstats

stats = leaguedashplayerstats.LeagueDashPlayerStats(
    season="2025-26",
    season_type_all_star="Regular Season",
    per_mode_detailed="PerGame"
).get_data_frames()[0]

candidate_stats = stats[
    stats["PLAYER_ID"].isin(candidate_pool["PLAYER_ID"])
].copy()

candidate_stats[
    [
        "PLAYER_NAME",
        "GP",
        "MIN",
        "PTS",
        "AST",
        "REB",
        "STL",
        "BLK",
        "TOV",
        "FG_PCT",
        "FG3_PCT",
        "FT_PCT"
    ]
].sort_values("PTS", ascending=False)

,PLAYER_NAME,GP,MIN,PTS,AST,REB,STL,BLK,TOV,FG_PCT,FG3_PCT,FT_PCT
372,Luka Dončić,64,35.8,33.5,8.3,7.7,1.6,0.5,4.0,0.476,0.366,0.780
501,Shai Gilgeous-Alexander,68,33.2,31.1,6.6,4.3,1.4,0.8,2.2,0.553,0.386,0.879
31,Anthony Edwards,61,35.0,28.8,3.7,5.0,1.4,0.8,2.9,0.489,0.399,0.796
260,Jaylen Brown,71,34.4,28.7,5.1,6.9,1.0,0.4,3.6,0.477,0.347,0.795
554,Tyrese Maxey,70,38.0,28.3,6.6,4.1,1.9,0.8,2.4,0.462,0.367,0.892
...,...,...,...,...,...,...,...,...,...,...,...,...
341,Khris Middleton,63,22.8,10.2,2.8,3.7,0.7,0.1,1.7,0.420,0.360,0.875
194,Harrison Barnes,77,25.8,9.9,1.9,2.8,0.6,0.2,0.8,0.456,0.388,0.829
291,Jordan Clarkson,72,17.8,8.6,1.3,1.8,0.4,0.1,0.9,0.451,0.327,0.830
53,Bradley Beal,6,20.2,8.2,1.7,0.8,0.5,0.0,1.5,0.375,0.368,0.750
68,Buddy Hield,51,16.1,7.6,1.4,2.3,0.8,0.2,0.9,0.437,0.349,0.811

In [23]:
from nba_api.stats.endpoints import leaguedashplayerstats

stats = leaguedashplayerstats.LeagueDashPlayerStats(
    season="2025-26",
    season_type_all_star="Regular Season",
    per_mode_detailed="PerGame"
).get_data_frames()[0]

candidate_stats = stats[
    stats["PLAYER_ID"].isin(candidate_pool["PLAYER_ID"])
].copy()

candidate_stats[
    [
        "PLAYER_NAME",
        "GP",
        "MIN",
        "PTS",
        "AST",
        "REB",
        "STL",
        "BLK",
        "TOV",
        "FG_PCT",
        "FG3_PCT",
        "FT_PCT"
    ]
].sort_values("PTS", ascending=False)

,PLAYER_NAME,GP,MIN,PTS,AST,REB,STL,BLK,TOV,FG_PCT,FG3_PCT,FT_PCT
372,Luka Dončić,64,35.8,33.5,8.3,7.7,1.6,0.5,4.0,0.476,0.366,0.780
501,Shai Gilgeous-Alexander,68,33.2,31.1,6.6,4.3,1.4,0.8,2.2,0.553,0.386,0.879
31,Anthony Edwards,61,35.0,28.8,3.7,5.0,1.4,0.8,2.9,0.489,0.399,0.796
260,Jaylen Brown,71,34.4,28.7,5.1,6.9,1.0,0.4,3.6,0.477,0.347,0.795
554,Tyrese Maxey,70,38.0,28.3,6.6,4.1,1.9,0.8,2.4,0.462,0.367,0.892
...,...,...,...,...,...,...,...,...,...,...,...,...
341,Khris Middleton,63,22.8,10.2,2.8,3.7,0.7,0.1,1.7,0.420,0.360,0.875
194,Harrison Barnes,77,25.8,9.9,1.9,2.8,0.6,0.2,0.8,0.456,0.388,0.829
291,Jordan Clarkson,72,17.8,8.6,1.3,1.8,0.4,0.1,0.9,0.451,0.327,0.830
53,Bradley Beal,6,20.2,8.2,1.7,0.8,0.5,0.0,1.5,0.375,0.368,0.750
68,Buddy Hield,51,16.1,7.6,1.4,2.3,0.8,0.2,0.9,0.437,0.349,0.811

In [24]:
candidate_stats["TS_PCT"] = candidate_stats["PTS"] / (
    2 * (
        candidate_stats["FGA"]
        + 0.44 * candidate_stats["FTA"]
    )
)

candidate_stats["EFG_PCT"] = (
    candidate_stats["FGM"]
    + 0.5 * candidate_stats["FG3M"]
) / candidate_stats["FGA"]

candidate_stats["THREE_PA_RATE"] = (
    candidate_stats["FG3A"] / candidate_stats["FGA"]
)

candidate_stats["FTA_RATE"] = (
    candidate_stats["FTA"] / candidate_stats["FGA"]
)

candidate_stats[
    [
        "PLAYER_NAME",
        "PTS",
        "AST",
        "REB",
        "TS_PCT",
        "EFG_PCT",
        "THREE_PA_RATE",
        "FTA_RATE"
    ]
].round(3)

,PLAYER_NAME,PTS,AST,REB,TS_PCT,EFG_PCT,THREE_PA_RATE,FTA_RATE
3,Aaron Gordon,16.2,2.7,5.8,0.619,0.572,0.396,0.405
21,Amen Thompson,18.3,5.3,7.8,0.596,0.549,0.114,0.371
27,Andrew Wiggins,15.4,2.7,4.8,0.585,0.554,0.405,0.198
28,Anfernee Simons,14.3,2.4,2.5,0.576,0.555,0.585,0.119
31,Anthony Edwards,28.8,3.7,5.0,0.616,0.574,0.416,0.356
...,...,...,...,...,...,...,...,...
550,Tyler Herro,20.5,4.1,4.8,0.601,0.561,0.429,0.212
554,Tyrese Maxey,28.3,6.6,4.1,0.589,0.535,0.402,0.280
559,Victor Wembanyama,25.0,3.1,11.5,0.626,0.565,0.325,0.414
577,Zach LaVine,19.2,2.3,2.8,0.616,0.568,0.464,0.257
580,Zion Williamson,21.0,3.2,5.7,0.644,0.600,0.008,0.577

In [25]:
output_path = Path("../data/processed/candidate_traditional_stats_2025_26.csv")
output_path.parent.mkdir(parents=True, exist_ok=True)

candidate_stats.to_csv(output_path, index=False)

print(f"Saved stats to: {output_path}")

Saved stats to: ..\data\processed\candidate_traditional_stats_2025_26.csv

In [26]:
candidate_stats.shape

(70, 73)

In [27]:
%pip install lxml

Requirement already satisfied: lxml in c:\Users\sachi\Documents\Aryan\kobe-similarity-project\kobe-similarity-analysis\.venv\Lib\site-packages (6.1.3)
Note: you may need to restart the kernel to use updated packages.

In [28]:
import pandas as pd

crafted_tables = pd.read_html(
    "https://craftednba.com/player-stats"
)

print("Number of tables:", len(crafted_tables))

for i, table in enumerate(crafted_tables):
    print("\nTABLE", i)
    print("Shape:", table.shape)
    print("Columns:")
    print(table.columns.tolist())

HTTPError: HTTP Error 403: Forbidden

In [ ]:
import requests
import pandas as pd
from io import StringIO

url = "https://craftednba.com/player-stats"

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/153.0.0.0 Safari/537.36"
    )
}

response = requests.get(url, headers=headers, timeout=30)

print("Status code:", response.status_code)

crafted_tables = pd.read_html(StringIO(response.text))

print("Number of tables:", len(crafted_tables))

for i, table in enumerate(crafted_tables):
    print("\nTABLE", i)
    print("Shape:", table.shape)
    print(table.columns.tolist())

Status code: 200
Number of tables: 1

TABLE 0
Shape: (575, 23)
[('Unnamed: 0_level_0', '#'), ('Unnamed: 1_level_0', 'Name'), ('Unnamed: 2_level_0', 'Age'), ('Traditional', 'MP'), ('Traditional', 'GP'), ('Traditional', 'MPG'), ('Traditional', 'FGM'), ('Traditional', 'FGA'), ('Traditional', 'FG%'), ('Traditional', '3PM'), ('Traditional', '3PA'), ('Traditional', '3P%'), ('Traditional', 'FTM'), ('Traditional', 'FTA'), ('Traditional', 'FT%'), ('Traditional', 'ORB'), ('Traditional', 'DRB'), ('Traditional', 'REB'), ('Traditional', 'AST'), ('Traditional', 'STL'), ('Traditional', 'BLK'), ('Traditional', 'TOV'), ('Traditional', 'PTS')]

In [ ]:
candidate_records = []

for name in candidate_names:
    matches = players.find_players_by_full_name(name)

    if matches:
        player = matches[0]

        candidate_records.append({
            "PLAYER_ID": player["id"],
            "PLAYER_NAME": player["full_name"]
        })
    else:
        print("NOT FOUND:", name)

candidate_pool = pd.DataFrame(candidate_records)

print(candidate_pool.shape)

(70, 2)

In [ ]:
kobe_reference_df = pd.DataFrame(
    [kobe_reference]
).T.reset_index()

kobe_reference_df.columns = ["Metric", "Kobe_Value"]

kobe_reference_df.round(3)

           Metric  Kobe_Value
0             MPG      36.139
1             PPG      24.995
2             APG       4.685
3             RPG       5.236
4             SPG       1.444
5             BPG       0.475
6            TOPG       2.979
7          FG_PCT       0.447
8         FG3_PCT       0.329
9          FT_PCT       0.837
10         TS_PCT       0.550
11        EFG_PCT       0.482
12  THREE_PA_RATE       0.212
13       FTA_RATE       0.382

In [ ]:
comparison_metrics = [
    "PTS",
    "AST",
    "REB",
    "STL",
    "BLK",
    "TOV",
    "FG_PCT",
    "FG3_PCT",
    "FT_PCT",
    "TS_PCT",
    "EFG_PCT",
    "THREE_PA_RATE",
    "FTA_RATE"
]

for metric in comparison_metrics:
    if metric in candidate_stats.columns and metric in kobe_reference:
        candidate_stats[f"{metric}_SIM"] = candidate_stats[metric].apply(
            lambda x: similarity_score(kobe_reference[metric], x)
        )

candidate_stats[
    ["PLAYER_NAME"] +
    [f"{m}_SIM" for m in comparison_metrics if f"{m}_SIM" in candidate_stats.columns]
].head()

,PLAYER_NAME,FG_PCT_SIM,FG3_PCT_SIM,FT_PCT_SIM,TS_PCT_SIM,EFG_PCT_SIM,THREE_PA_RATE_SIM,FTA_RATE_SIM
3,Aaron Gordon,88.886424,81.916037,91.650000,87.331460,81.351369,12.737368,93.900493
21,Amen Thompson,80.614387,65.568473,93.083898,91.590240,86.086273,53.683244,97.150710
27,Andrew Wiggins,93.804932,74.327094,93.681356,93.514064,85.157823,8.692439,51.909841
28,Anfernee Simons,98.370168,83.130268,92.935593,95.226915,84.874567,0.000000,31.050590
31,Anthony Edwards,90.674972,78.880460,95.115254,87.884324,80.898123,3.551217,93.283527

In [ ]:
similarity_columns = [
    f"{m}_SIM"
    for m in comparison_metrics
    if f"{m}_SIM" in candidate_stats.columns
]

candidate_stats["TRADITIONAL_SIMILARITY"] = (
    candidate_stats[similarity_columns].mean(axis=1)
)

candidate_stats[
    ["PLAYER_NAME", "TRADITIONAL_SIMILARITY"]
].sort_values(
    "TRADITIONAL_SIMILARITY",
    ascending=False
).head(10)

         PLAYER_NAME  TRADITIONAL_SIMILARITY
178     Franz Wagner               90.981042
260     Jaylen Brown               90.856029
239   Jalen Williams               90.166134
454   Paolo Banchero               90.121196
310    Julius Randle               89.376946
135    DeMar DeRozan               89.106131
496   Scottie Barnes               88.965677
146     Devin Booker               88.889144
71   Cade Cunningham               88.626996
455    Pascal Siakam               88.567516

In [ ]:
candidate_names = [
    "Shai Gilgeous-Alexander",
    "Luka Doncic",
    "Anthony Edwards",
    "Devin Booker",
    "Jalen Brunson",
    "Jaylen Brown",
    "Jayson Tatum",
    "Kevin Durant",
    "Kawhi Leonard",
    "Jimmy Butler",
    "LeBron James",
    "Donovan Mitchell",
    "Ja Morant",
    "De'Aaron Fox",
    "Tyrese Maxey",
    "Cade Cunningham",
    "Trae Young",
    "Jamal Murray",
    "Stephen Curry",
    "Nikola Jokic",
    "LaMelo Ball",
    "Darius Garland",
    "Desmond Bane",
    "Brandon Ingram",
    "Mikal Bridges",
    "OG Anunoby",
    "RJ Barrett",
    "Scottie Barnes",
    "Paolo Banchero",
    "Franz Wagner",
    "Jalen Johnson",
    "Julius Randle",
    "Deni Avdija",
    "Brandon Miller",
    "Cam Thomas",
    "Anfernee Simons",
    "Jordan Poole",
    "Tyler Herro",
    "Dejounte Murray",
    "CJ McCollum",
    "DeMar DeRozan",
    "Michael Porter Jr.",
    "Zach LaVine",
    "Norman Powell",
    "Bradley Beal",
    "Khris Middleton",
    "Andrew Wiggins",
    "Aaron Gordon",
    "Jerami Grant",
    "Miles Bridges",
    "Trey Murphy III",
    "Jaden McDaniels",
    "Austin Reaves",
    "Collin Sexton",
    "Jordan Clarkson",
    "Buddy Hield",
    "Klay Thompson",
    "Harrison Barnes",
    "Zion Williamson",
    "Pascal Siakam",
    "Lauri Markkanen",
    "Chet Holmgren",
    "Bam Adebayo",
    "Paul George",
    "Jrue Holiday",
    "Jalen Green",
    "Amen Thompson",
    "Devin Vassell",
    "Victor Wembanyama",
    "Jalen Williams"
]

print(len(candidate_names))

70

In [ ]:
from nba_api.stats.static import players
import pandas as pd

candidate_records = []

for name in candidate_names:
    matches = players.find_players_by_full_name(name)

    if matches:
        player = matches[0]

        candidate_records.append({
            "PLAYER_ID": player["id"],
            "PLAYER_NAME": player["full_name"]
        })
    else:
        print("NOT FOUND:", name)

candidate_pool = pd.DataFrame(candidate_records)

print(candidate_pool.shape)

(70, 2)

In [ ]:
from pathlib import Path

output_path = Path("../data/manual/candidate_pool.csv")
output_path.parent.mkdir(parents=True, exist_ok=True)

candidate_pool.to_csv(output_path, index=False)

print(f"Saved candidate pool to: {output_path}")

Saved candidate pool to: ..\data\manual\candidate_pool.csv

In [ ]:
print("Candidates:", len(candidate_pool))
print("Candidate stats:", candidate_stats.shape)

Candidates: 70
Candidate stats: (70, 73)

In [ ]:
from nba_api.stats.endpoints import leaguedashplayerstats

advanced_stats = leaguedashplayerstats.LeagueDashPlayerStats(
    season="2025-26",
    season_type_all_star="Regular Season",
    per_mode_detailed="PerGame"
).get_data_frames()[0]

print("Shape:", advanced_stats.shape)
print("Columns:")
print(advanced_stats.columns.tolist())

Shape: (582, 69)
Columns:
['PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID', 'TEAM_ABBREVIATION', 'AGE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS', 'NBA_FANTASY_PTS', 'DD2', 'TD3', 'WNBA_FANTASY_PTS', 'FP_HIGH_SCORE', 'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK', 'REB_RANK', 'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK', 'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK', 'DD2_RANK', 'TD3_RANK', 'WNBA_FANTASY_PTS_RANK', 'FP_HIGH_SCORE_RANK', 'TEAM_COUNT']

In [ ]:
advanced_candidates = advanced_stats[
    advanced_stats["PLAYER_ID"].isin(candidate_pool["PLAYER_ID"])
].copy()

print("Advanced candidate shape:", advanced_candidates.shape)

Advanced candidate shape: (70, 69)

In [ ]:
useful_columns = [
    "PLAYER_NAME",
    "PLAYER_ID",
    "MIN",
    "PTS",
    "FG_PCT",
    "FG3_PCT",
    "FT_PCT",
    "AST",
    "REB",
    "STL",
    "BLK",
    "TOV",
    "USG_PCT",
    "AST_PCT",
    "REB_PCT",
    "TOV_PCT",
    "STL_PCT",
    "BLK_PCT"
]

available_columns = [
    col for col in useful_columns
    if col in advanced_candidates.columns
]

advanced_candidates[available_columns].head(10)

,PLAYER_NAME,PLAYER_ID,MIN,PTS,FG_PCT,FG3_PCT,FT_PCT,AST,REB,STL,BLK,TOV
3,Aaron Gordon,203932,27.9,16.2,0.497,0.389,0.767,2.7,5.8,0.6,0.3,1.1
21,Amen Thompson,1641708,37.4,18.3,0.534,0.216,0.779,5.3,7.8,1.5,0.6,2.4
27,Andrew Wiggins,203952,30.3,15.4,0.475,0.414,0.784,2.7,4.8,1.1,1.0,1.5
28,Anfernee Simons,1629014,24.9,14.3,0.440,0.385,0.896,2.4,2.5,0.5,0.1,1.2
31,Anthony Edwards,1630162,35.0,28.8,0.489,0.399,0.796,3.7,5.0,1.4,0.8,2.9
37,Austin Reaves,1630559,34.5,23.3,0.490,0.360,0.871,5.5,4.7,1.1,0.4,3.0
39,Bam Adebayo,1628389,32.4,20.1,0.442,0.318,0.778,3.2,10.0,1.2,0.7,1.6
53,Bradley Beal,203078,20.2,8.2,0.375,0.368,0.750,1.7,0.8,0.5,0.0,1.5
57,Brandon Ingram,1627742,33.8,21.5,0.477,0.382,0.820,3.7,5.6,0.8,0.7,2.4
58,Brandon Miller,1641706,30.3,20.2,0.435,0.383,0.892,3.3,4.9,1.0,0.7,2.5

In [ ]:
advanced_stats.columns.tolist()

['PLAYER_ID',
 'PLAYER_NAME',
 'NICKNAME',
 'TEAM_ID',
 'TEAM_ABBREVIATION',
 'AGE',
 'GP',
 'W',
 'L',
 'W_PCT',
 'MIN',
 'FGM',
 'FGA',
 'FG_PCT',
 'FG3M',
 'FG3A',
 'FG3_PCT',
 'FTM',
 'FTA',
 'FT_PCT',
 'OREB',
 'DREB',
 'REB',
 'AST',
 'TOV',
 'STL',
 'BLK',
 'BLKA',
 'PF',
 'PFD',
 'PTS',
 'PLUS_MINUS',
 'NBA_FANTASY_PTS',
 'DD2',
 'TD3',
 'WNBA_FANTASY_PTS',
 'FP_HIGH_SCORE',
 'GP_RANK',
 'W_RANK',
 'L_RANK',
 'W_PCT_RANK',
 'MIN_RANK',
 'FGM_RANK',
 'FGA_RANK',
 'FG_PCT_RANK',
 'FG3M_RANK',
 'FG3A_RANK',
 'FG3_PCT_RANK',
 'FTM_RANK',
 'FTA_RANK',
 'FT_PCT_RANK',
 'OREB_RANK',
 'DREB_RANK',
 'REB_RANK',
 'AST_RANK',
 'TOV_RANK',
 'STL_RANK',
 'BLK_RANK',
 'BLKA_RANK',
 'PF_RANK',
 'PFD_RANK',
 'PTS_RANK',
 'PLUS_MINUS_RANK',
 'NBA_FANTASY_PTS_RANK',
 'DD2_RANK',
 'TD3_RANK',
 'WNBA_FANTASY_PTS_RANK',
 'FP_HIGH_SCORE_RANK',
 'TEAM_COUNT']

In [ ]:
advanced_candidates.shape

(70, 69)

In [ ]:
for i, col in enumerate(advanced_stats.columns):
    print(i, col)

0 PLAYER_ID
1 PLAYER_NAME
2 NICKNAME
3 TEAM_ID
4 TEAM_ABBREVIATION
5 AGE
6 GP
7 W
8 L
9 W_PCT
10 MIN
11 FGM
12 FGA
13 FG_PCT
14 FG3M
15 FG3A
16 FG3_PCT
17 FTM
18 FTA
19 FT_PCT
20 OREB
21 DREB
22 REB
23 AST
24 TOV
25 STL
26 BLK
27 BLKA
28 PF
29 PFD
30 PTS
31 PLUS_MINUS
32 NBA_FANTASY_PTS
33 DD2
34 TD3
35 WNBA_FANTASY_PTS
36 FP_HIGH_SCORE
37 GP_RANK
38 W_RANK
39 L_RANK
40 W_PCT_RANK
41 MIN_RANK
42 FGM_RANK
43 FGA_RANK
44 FG_PCT_RANK
45 FG3M_RANK
46 FG3A_RANK
47 FG3_PCT_RANK
48 FTM_RANK
49 FTA_RANK
50 FT_PCT_RANK
51 OREB_RANK
52 DREB_RANK
53 REB_RANK
54 AST_RANK
55 TOV_RANK
56 STL_RANK
57 BLK_RANK
58 BLKA_RANK
59 PF_RANK
60 PFD_RANK
61 PTS_RANK
62 PLUS_MINUS_RANK
63 NBA_FANTASY_PTS_RANK
64 DD2_RANK
65 TD3_RANK
66 WNBA_FANTASY_PTS_RANK
67 FP_HIGH_SCORE_RANK
68 TEAM_COUNT

In [ ]:
advanced_candidates = advanced_stats[
    advanced_stats["PLAYER_ID"].isin(candidate_pool["PLAYER_ID"])
].copy()

advanced_candidates.head()

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,FP_HIGH_SCORE_RANK,TEAM_COUNT
3,203932,Aaron Gordon,Aaron,1610612743,DEN,30.0,36,27,9,0.750,...,274,66,88,12,113,114,38,111,124,1
21,1641708,Amen Thompson,Amen,1610612745,HOU,23.0,79,49,30,0.620,...,140,48,60,49,35,21,38,41,33,1
27,203952,Andrew Wiggins,Andrew,1610612748,MIA,31.0,68,35,33,0.515,...,122,180,93,241,99,159,38,97,103,1
28,1629014,Anfernee Simons,Anfernee,1610612741,CHI,27.0,55,31,24,0.564,...,278,317,109,134,208,284,38,165,197,2
31,1630162,Anthony Edwards,Anthony,1610612750,MIN,24.0,61,37,24,0.607,...,226,29,3,100,15,159,38,10,18,1

In [ ]:
measure_type_detailed_defense="Advanced"

In [ ]:
advanced_stats = leaguedashplayerstats.LeagueDashPlayerStats(
    season="2025-26",
    season_type_all_star="Regular Season",
    measure_type_detailed_defense="Advanced",
    per_mode_detailed="PerGame"
).get_data_frames()[0]

print("Shape:", advanced_stats.shape)
print(advanced_stats.columns.tolist())

Shape: (582, 79)
['PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID', 'TEAM_ABBREVIATION', 'AGE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'E_OFF_RATING', 'OFF_RATING', 'sp_work_OFF_RATING', 'E_DEF_RATING', 'DEF_RATING', 'sp_work_DEF_RATING', 'E_NET_RATING', 'NET_RATING', 'sp_work_NET_RATING', 'AST_PCT', 'AST_TO', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT', 'E_TOV_PCT', 'EFG_PCT', 'TS_PCT', 'USG_PCT', 'E_USG_PCT', 'E_PACE', 'PACE', 'PACE_PER40', 'sp_work_PACE', 'PIE', 'POSS', 'FGM', 'FGA', 'FGM_PG', 'FGA_PG', 'FG_PCT', 'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'E_OFF_RATING_RANK', 'OFF_RATING_RANK', 'sp_work_OFF_RATING_RANK', 'E_DEF_RATING_RANK', 'DEF_RATING_RANK', 'sp_work_DEF_RATING_RANK', 'E_NET_RATING_RANK', 'NET_RATING_RANK', 'sp_work_NET_RATING_RANK', 'AST_PCT_RANK', 'AST_TO_RANK', 'AST_RATIO_RANK', 'OREB_PCT_RANK', 'DREB_PCT_RANK', 'REB_PCT_RANK', 'TM_TOV_PCT_RANK', 'E_TOV_PCT_RANK', 'EFG_PCT_RANK', 'TS_PCT_RANK', 'USG_PCT_RANK', 'E_USG_PCT_RANK', 'E_PACE_RANK', 'PACE_RANK', 'sp_work_PACE_RANK', 'PIE_RANK', 'FGM_RANK', 'FGA_RANK', 'FGM_PG_RANK', 'FGA_PG_RANK', 'FG_PCT_RANK', 'TEAM_COUNT']

In [ ]:
advanced_candidates = advanced_stats[
    advanced_stats["PLAYER_ID"].isin(candidate_pool["PLAYER_ID"])
].copy()

print("Advanced candidates:", advanced_candidates.shape)

Advanced candidates: (70, 79)

In [ ]:
advanced_candidates.head()

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,E_PACE_RANK,PACE_RANK,sp_work_PACE_RANK,PIE_RANK,FGM_RANK,FGA_RANK,FGM_PG_RANK,FGA_PG_RANK,FG_PCT_RANK,TEAM_COUNT
3,203932,Aaron Gordon,Aaron,1610612743,DEN,30.0,36,27,9,0.750,...,394,426,426,104,215,229,101,119,168,1
21,1641708,Amen Thompson,Amen,1610612745,HOU,23.0,79,49,30,0.620,...,485,506,506,78,20,35,46,71,99,1
27,203952,Andrew Wiggins,Andrew,1610612748,MIA,31.0,68,35,33,0.515,...,52,82,82,257,73,66,87,92,229,1
28,1629014,Anfernee Simons,Anfernee,1610612741,CHI,27.0,55,31,24,0.564,...,499,554,554,231,133,117,121,98,349,2
31,1630162,Anthony Edwards,Anthony,1610612750,MIN,24.0,61,37,24,0.607,...,226,314,314,36,12,12,7,4,187,1

In [ ]:

advanced_candidates = advanced_stats[
    advanced_stats["PLAYER_ID"].isin(candidate_pool["PLAYER_ID"])
].copy()

print("Advanced candidates:", advanced_candidates.shape)

Advanced candidates: (70, 79)

In [ ]:
[col for col in advanced_candidates.columns if "TOV" in col or "TO_" in col]

['TM_TOV_PCT', 'E_TOV_PCT', 'AST_TO_RANK', 'TM_TOV_PCT_RANK', 'E_TOV_PCT_RANK']

In [ ]:
print(advanced_candidates.columns.tolist())

['PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID', 'TEAM_ABBREVIATION', 'AGE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'E_OFF_RATING', 'OFF_RATING', 'sp_work_OFF_RATING', 'E_DEF_RATING', 'DEF_RATING', 'sp_work_DEF_RATING', 'E_NET_RATING', 'NET_RATING', 'sp_work_NET_RATING', 'AST_PCT', 'AST_TO', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT', 'E_TOV_PCT', 'EFG_PCT', 'TS_PCT', 'USG_PCT', 'E_USG_PCT', 'E_PACE', 'PACE', 'PACE_PER40', 'sp_work_PACE', 'PIE', 'POSS', 'FGM', 'FGA', 'FGM_PG', 'FGA_PG', 'FG_PCT', 'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'E_OFF_RATING_RANK', 'OFF_RATING_RANK', 'sp_work_OFF_RATING_RANK', 'E_DEF_RATING_RANK', 'DEF_RATING_RANK', 'sp_work_DEF_RATING_RANK', 'E_NET_RATING_RANK', 'NET_RATING_RANK', 'sp_work_NET_RATING_RANK', 'AST_PCT_RANK', 'AST_TO_RANK', 'AST_RATIO_RANK', 'OREB_PCT_RANK', 'DREB_PCT_RANK', 'REB_PCT_RANK', 'TM_TOV_PCT_RANK', 'E_TOV_PCT_RANK', 'EFG_PCT_RANK', 'TS_PCT_RANK', 'USG_PCT_RANK', 'E_USG_PCT_RANK', 'E_PACE_RANK', 'PACE_RANK', 'sp_work_PACE_RANK', 'PIE_RANK', 'FGM_RANK', 'FGA_RANK', 'FGM_PG_RANK', 'FGA_PG_RANK', 'FG_PCT_RANK', 'TEAM_COUNT']

In [ ]:
advanced_metric_columns = [
    "PLAYER_NAME",
    "PLAYER_ID",
    "MIN",
    "OFF_RATING",
    "DEF_RATING",
    "NET_RATING",
    "AST_PCT",
    "AST_TO",
    "OREB_PCT",
    "DREB_PCT",
    "REB_PCT",
    "E_TOV_PCT",
    "USG_PCT",
    "TS_PCT",
    "EFG_PCT",
    "PACE",
    "PIE"
]

available_advanced_metrics = [
    col for col in advanced_metric_columns
    if col in advanced_candidates.columns
]

advanced_candidates[available_advanced_metrics].head(10)

,PLAYER_NAME,PLAYER_ID,MIN,OFF_RATING,DEF_RATING,NET_RATING,AST_PCT,AST_TO,OREB_PCT,DREB_PCT,REB_PCT,E_TOV_PCT,USG_PCT,TS_PCT,EFG_PCT,PACE,PIE
3,Aaron Gordon,203932,27.9,124.7,112.0,12.7,0.130,2.53,0.052,0.148,0.102,6.3,0.213,0.620,0.574,99.99,0.117
21,Amen Thompson,1641708,37.4,117.0,110.4,6.6,0.202,2.21,0.078,0.123,0.101,10.4,0.195,0.594,0.545,98.40,0.128
27,Andrew Wiggins,203952,30.3,113.7,113.9,-0.1,0.123,1.77,0.051,0.098,0.074,8.7,0.194,0.586,0.559,104.97,0.092
28,Anfernee Simons,1629014,24.9,116.9,114.0,3.0,0.151,1.97,0.021,0.075,0.047,7.7,0.227,0.576,0.552,97.42,0.096
31,Anthony Edwards,1630162,35.0,117.8,114.3,3.5,0.174,1.30,0.017,0.120,0.069,9.5,0.309,0.617,0.572,101.50,0.145
37,Austin Reaves,1630559,34.5,117.3,112.3,5.0,0.237,1.85,0.020,0.117,0.071,11.1,0.258,0.641,0.567,100.41,0.137
39,Bam Adebayo,1628389,32.4,117.1,111.0,6.1,0.142,1.93,0.059,0.236,0.146,7.1,0.248,0.551,0.497,103.89,0.138
53,Bradley Beal,203078,20.2,119.1,128.5,-9.3,0.106,1.11,0.019,0.025,0.022,12.8,0.224,0.476,0.448,97.65,0.018
57,Brandon Ingram,1627742,33.8,114.6,113.7,1.0,0.169,1.52,0.024,0.144,0.083,9.8,0.264,0.573,0.529,98.87,0.121
58,Brandon Miller,1641706,30.3,119.8,111.3,8.5,0.173,1.33,0.034,0.122,0.078,10.7,0.272,0.574,0.533,98.44,0.113

In [ ]:
print("Metrics available:")
print(available_advanced_metrics)

Metrics available:
['PLAYER_NAME', 'PLAYER_ID', 'MIN', 'OFF_RATING', 'DEF_RATING', 'NET_RATING', 'AST_PCT', 'AST_TO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'E_TOV_PCT', 'USG_PCT', 'TS_PCT', 'EFG_PCT', 'PACE', 'PIE']

In [ ]:
from pathlib import Path

advanced_clean = advanced_candidates[available_advanced_metrics].copy()

output_path = Path("../data/processed/candidate_advanced_clean_2025_26.csv")
output_path.parent.mkdir(parents=True, exist_ok=True)

advanced_clean.to_csv(output_path, index=False)

print(f"Saved to: {output_path}")

Saved to: ..\data\processed\candidate_advanced_clean_2025_26.csv

In [ ]:
from pathlib import Path

advanced_clean = advanced_candidates[available_advanced_metrics].copy()

output_path = Path("../data/processed/candidate_advanced_clean_2025_26.csv")
output_path.parent.mkdir(parents=True, exist_ok=True)

advanced_clean.to_csv(output_path, index=False)

print(f"Saved to: {output_path}")

Saved to: ..\data\processed\candidate_advanced_clean_2025_26.csv

In [ ]:
from nba_api.stats.endpoints import leaguedashplayerstats
import pandas as pd
import time

kobe_advanced_seasons = []

for season in df["SEASON_ID"]:
    try:
        season_stats = leaguedashplayerstats.LeagueDashPlayerStats(
            season=season,
            season_type_all_star="Regular Season",
            measure_type_detailed_defense="Advanced",
            per_mode_detailed="PerGame"
        ).get_data_frames()[0]

        kobe_season = season_stats[
            season_stats["PLAYER_ID"] == 977
        ].copy()

        if not kobe_season.empty:
            kobe_season["SEASON_ID"] = season
            kobe_advanced_seasons.append(kobe_season)

        print(season, "done")

        time.sleep(0.5)

    except Exception as e:
        print(season, "ERROR:", e)

kobe_advanced = pd.concat(
    kobe_advanced_seasons,
    ignore_index=True
)

print("\nKobe advanced seasons:", kobe_advanced.shape)

1996-97 done
1997-98 done
1998-99 done
1999-00 done
2000-01 done
2001-02 done
2002-03 done
2003-04 done
2004-05 done
2005-06 done
2006-07 done
2007-08 done
2008-09 done
2009-10 done
2010-11 done
2011-12 done
2012-13 done
2013-14 done
2014-15 done
2015-16 done

Kobe advanced seasons: (20, 80)

In [ ]:
key_advanced = [
    "OFF_RATING",
    "DEF_RATING",
    "NET_RATING",
    "AST_PCT",
    "AST_TO",
    "REB_PCT",
    "E_TOV_PCT",
    "USG_PCT",
    "TS_PCT",
    "EFG_PCT",
    "PACE",
    "PIE"
]

coverage = pd.DataFrame({
    "metric": key_advanced,
    "seasons_available": [
        kobe_advanced[m].notna().sum()
        for m in key_advanced
    ],
    "seasons_missing": [
        kobe_advanced[m].isna().sum()
        for m in key_advanced
    ]
})

coverage

        metric  seasons_available  seasons_missing
0   OFF_RATING                 20                0
1   DEF_RATING                 20                0
2   NET_RATING                 20                0
3      AST_PCT                 20                0
4       AST_TO                 20                0
5      REB_PCT                 20                0
6    E_TOV_PCT                 20                0
7      USG_PCT                 20                0
8       TS_PCT                 20                0
9      EFG_PCT                 20                0
10        PACE                 20                0
11         PIE                 20                0

In [ ]:
advanced_reference_metrics = [
    "OFF_RATING",
    "DEF_RATING",
    "NET_RATING",
    "AST_PCT",
    "AST_TO",
    "REB_PCT",
    "E_TOV_PCT",
    "USG_PCT",
    "TS_PCT",
    "EFG_PCT",
    "PACE",
    "PIE"
]

# Advanced stats are per-game/per-possession measures,
# so use total minutes as the career weighting factor.
kobe_advanced["TOTAL_MIN"] = (
    kobe_advanced["MIN"] * kobe_advanced["GP"]
)

kobe_advanced_reference = {}

for metric in advanced_reference_metrics:
    valid = kobe_advanced[["TOTAL_MIN", metric]].dropna()

    kobe_advanced_reference[metric] = (
        (valid[metric] * valid["TOTAL_MIN"]).sum()
        / valid["TOTAL_MIN"].sum()
    )

kobe_advanced_reference_df = pd.DataFrame({
    "Metric": kobe_advanced_reference.keys(),
    "Kobe_Value": kobe_advanced_reference.values()
})

kobe_advanced_reference_df.round(3)

        Metric  Kobe_Value
0   OFF_RATING     108.128
1   DEF_RATING     104.011
2   NET_RATING       4.125
3      AST_PCT       0.237
4       AST_TO       1.588
5      REB_PCT       0.072
6    E_TOV_PCT       9.875
7      USG_PCT       0.311
8       TS_PCT       0.550
9      EFG_PCT       0.482
10        PACE      94.839
11         PIE       0.151

In [ ]:
from pathlib import Path

output_path = Path("../data/processed/kobe_advanced_reference.csv")
output_path.parent.mkdir(parents=True, exist_ok=True)

kobe_advanced_reference_df.to_csv(
    output_path,
    index=False
)

print(f"Saved to: {output_path}")

Saved to: ..\data\processed\kobe_advanced_reference.csv

In [ ]:
output_path = Path("../data/processed/candidate_advanced_clean_2025_26.csv")
output_path.parent.mkdir(parents=True, exist_ok=True)

advanced_clean.to_csv(
    output_path,
    index=False
)

print(f"Saved to: {output_path}")
print("Shape:", advanced_clean.shape)

Saved to: ..\data\processed\candidate_advanced_clean_2025_26.csv
Shape: (70, 17)

In [ ]:
print("Kobe advanced reference:")
display(kobe_advanced_reference_df.round(3))

print("\nCandidate advanced data:")
display(advanced_clean.head())

Kobe advanced reference:

        Metric  Kobe_Value
0   OFF_RATING     108.128
1   DEF_RATING     104.011
2   NET_RATING       4.125
3      AST_PCT       0.237
4       AST_TO       1.588
5      REB_PCT       0.072
6    E_TOV_PCT       9.875
7      USG_PCT       0.311
8       TS_PCT       0.550
9      EFG_PCT       0.482
10        PACE      94.839
11         PIE       0.151

Candidate advanced data:

,PLAYER_NAME,PLAYER_ID,MIN,OFF_RATING,DEF_RATING,NET_RATING,AST_PCT,AST_TO,OREB_PCT,DREB_PCT,REB_PCT,E_TOV_PCT,USG_PCT,TS_PCT,EFG_PCT,PACE,PIE
3,Aaron Gordon,203932,27.9,124.7,112.0,12.7,0.130,2.53,0.052,0.148,0.102,6.3,0.213,0.620,0.574,99.99,0.117
21,Amen Thompson,1641708,37.4,117.0,110.4,6.6,0.202,2.21,0.078,0.123,0.101,10.4,0.195,0.594,0.545,98.40,0.128
27,Andrew Wiggins,203952,30.3,113.7,113.9,-0.1,0.123,1.77,0.051,0.098,0.074,8.7,0.194,0.586,0.559,104.97,0.092
28,Anfernee Simons,1629014,24.9,116.9,114.0,3.0,0.151,1.97,0.021,0.075,0.047,7.7,0.227,0.576,0.552,97.42,0.096
31,Anthony Edwards,1630162,35.0,117.8,114.3,3.5,0.174,1.30,0.017,0.120,0.069,9.5,0.309,0.617,0.572,101.50,0.145

In [ ]:
print("Kobe reference shape:", kobe_advanced_reference_df.shape)
print("Candidate advanced shape:", advanced_clean.shape)

print("\nKobe reference file:")
print(Path("../data/processed/kobe_advanced_reference.csv").exists())

print("\nCandidate advanced file:")
print(Path("../data/processed/candidate_advanced_clean_2025_26.csv").exists())

Kobe reference shape: (12, 2)
Candidate advanced shape: (70, 17)

Kobe reference file:
True

Candidate advanced file:
True

## Day 5 - Metric Mapping

In [ ]:
from nba_api.stats.endpoints import leaguedashplayerptshot

shot_test = leaguedashplayerptshot.LeagueDashPlayerPtShot(
    season="2025-26",
    season_type_all_star="Regular Season",
    per_mode_simple="PerGame"
)

shot_test_df = shot_test.get_data_frames()[0]

print(shot_test_df.shape)
print(shot_test_df.columns.tolist())

(582, 20)
['PLAYER_ID', 'PLAYER_NAME', 'PLAYER_LAST_TEAM_ID', 'PLAYER_LAST_TEAM_ABBREVIATION', 'AGE', 'GP', 'G', 'FGA_FREQUENCY', 'FGM', 'FGA', 'FG_PCT', 'EFG_PCT', 'FG2A_FREQUENCY', 'FG2M', 'FG2A', 'FG2_PCT', 'FG3A_FREQUENCY', 'FG3M', 'FG3A', 'FG3_PCT']

In [ ]:
print(shot_test_df.columns.tolist())

['PLAYER_ID', 'PLAYER_NAME', 'PLAYER_LAST_TEAM_ID', 'PLAYER_LAST_TEAM_ABBREVIATION', 'AGE', 'GP', 'G', 'FGA_FREQUENCY', 'FGM', 'FGA', 'FG_PCT', 'EFG_PCT', 'FG2A_FREQUENCY', 'FG2M', 'FG2A', 'FG2_PCT', 'FG3A_FREQUENCY', 'FG3M', 'FG3A', 'FG3_PCT']

In [ ]:
print("Shot profile columns:")
for i, col in enumerate(shot_test_df.columns):
    print(i, col)

Shot profile columns:
0 PLAYER_ID
1 PLAYER_NAME
2 PLAYER_LAST_TEAM_ID
3 PLAYER_LAST_TEAM_ABBREVIATION
4 AGE
5 GP
6 G
7 FGA_FREQUENCY
8 FGM
9 FGA
10 FG_PCT
11 EFG_PCT
12 FG2A_FREQUENCY
13 FG2M
14 FG2A
15 FG2_PCT
16 FG3A_FREQUENCY
17 FG3M
18 FG3A
19 FG3_PCT

In [ ]:
shot_keywords = [
    "FREQUENCY",
    "FGM",
    "FGA",
    "FG_PCT",
    "FG3",
    "MID",
    "PAINT",
    "RIM",
    "CORNER",
    "ABOVE",
    "LEFT",
    "RIGHT"
]

shot_relevant = [
    col for col in shot_test_df.columns
    if any(keyword in col.upper() for keyword in shot_keywords)
]

print("Potentially useful shot metrics:")
print(shot_relevant)

Potentially useful shot metrics:
['FGA_FREQUENCY', 'FGM', 'FGA', 'FG_PCT', 'EFG_PCT', 'FG2A_FREQUENCY', 'FG3A_FREQUENCY', 'FG3M', 'FG3A', 'FG3_PCT']

In [31]:
from nba_api.stats.endpoints import leaguedashplayershotlocations

shot_locations_test = leaguedashplayershotlocations.LeagueDashPlayerShotLocations(
    season="2025-26",
    season_type_all_star="Regular Season",
    measure_type_simple="Base",
    distance_range="By Zone",
    per_mode_detailed="PerGame",
    pace_adjust="N",
    plus_minus="N",
    rank="N"
)

test_df = shot_locations_test.get_data_frames()[0]

print(test_df.shape)
print(test_df.head())
print(test_df.columns)

(582, 30)
SHOT_CATEGORY                                                               \
columns       PLAYER_ID    PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION   AGE
0               1630639    A.J. Lawson  1610612761               TOR  25.0
1               1631260       AJ Green  1610612749               MIL  26.0
2               1642358     AJ Johnson  1610612742               DAL  21.0
3                203932   Aaron Gordon  1610612743               DEN  30.0
4               1628988  Aaron Holiday  1610612745               HOU  29.0

SHOT_CATEGORY          Restricted Area             In The Paint (Non-RA)  ...  \
columns       NICKNAME             FGM  FGA FG_PCT                   FGM  ...
0                 A.J.             0.6  1.2  0.519                   0.0  ...
1                   AJ             0.1  0.2  0.579                   0.1  ...
2                   AJ             0.8  1.8  0.429                   0.3  ...
3                Aaron             2.7  3.6  0.752                   0.6  ...
4                Aaron             0.2  0.4  0.591                   0.4  ...

SHOT_CATEGORY Right Corner 3 Above the Break 3             Backcourt       \
columns               FG_PCT               FGM  FGA FG_PCT       FGM  FGA
0                      0.364               0.2  0.6  0.385       0.0  0.0
1                      0.479               2.0  5.2  0.393       0.0  0.0
2                      0.286               0.2  1.0  0.196       0.0  0.0
3                      0.524               1.1  3.1  0.369       0.0  0.0
4                      0.455               0.7  2.1  0.359       0.0  0.0

SHOT_CATEGORY        Corner 3
columns       FG_PCT      FGM  FGA FG_PCT
0                0.0      0.7  1.6  0.438
1                0.0      0.9  1.9  0.487
2                0.0      0.1  0.3  0.273
3                0.0      0.6  1.3  0.435
4                0.0      0.5  1.1  0.472

[5 rows x 30 columns]
MultiIndex([(                     '',         'PLAYER_ID'),
            (                     '',       'PLAYER_NAME'),
            (                     '',           'TEAM_ID'),
            (                     '', 'TEAM_ABBREVIATION'),
            (                     '',               'AGE'),
            (                     '',          'NICKNAME'),
            (      'Restricted Area',               'FGM'),
            (      'Restricted Area',               'FGA'),
            (      'Restricted Area',            'FG_PCT'),
            ('In The Paint (Non-RA)',               'FGM'),
            ('In The Paint (Non-RA)',               'FGA'),
            ('In The Paint (Non-RA)',            'FG_PCT'),
            (            'Mid-Range',               'FGM'),
            (            'Mid-Range',               'FGA'),
            (            'Mid-Range',            'FG_PCT'),
            (        'Left Corner 3',               'FGM'),
            (        'Left Corner 3',               'FGA'),
            (        'Left Corner 3',            'FG_PCT'),
            (       'Right Corner 3',               'FGM'),
            (       'Right Corner 3',               'FGA'),
            (       'Right Corner 3',            'FG_PCT'),
            (    'Above the Break 3',               'FGM'),
            (    'Above the Break 3',               'FGA'),
            (    'Above the Break 3',            'FG_PCT'),
            (            'Backcourt',               'FGM'),
            (            'Backcourt',               'FGA'),
            (            'Backcourt',            'FG_PCT'),
            (             'Corner 3',               'FGM'),
            (             'Corner 3',               'FGA'),
            (             'Corner 3',            'FG_PCT')],
           names=['SHOT_CATEGORY', 'columns'])

In [32]:
print(test_df.shape)
print(test_df.columns)

(582, 30)
MultiIndex([(                     '',         'PLAYER_ID'),
            (                     '',       'PLAYER_NAME'),
            (                     '',           'TEAM_ID'),
            (                     '', 'TEAM_ABBREVIATION'),
            (                     '',               'AGE'),
            (                     '',          'NICKNAME'),
            (      'Restricted Area',               'FGM'),
            (      'Restricted Area',               'FGA'),
            (      'Restricted Area',            'FG_PCT'),
            ('In The Paint (Non-RA)',               'FGM'),
            ('In The Paint (Non-RA)',               'FGA'),
            ('In The Paint (Non-RA)',            'FG_PCT'),
            (            'Mid-Range',               'FGM'),
            (            'Mid-Range',               'FGA'),
            (            'Mid-Range',            'FG_PCT'),
            (        'Left Corner 3',               'FGM'),
            (        'Left Corner 3',               'FGA'),
            (        'Left Corner 3',            'FG_PCT'),
            (       'Right Corner 3',               'FGM'),
            (       'Right Corner 3',               'FGA'),
            (       'Right Corner 3',            'FG_PCT'),
            (    'Above the Break 3',               'FGM'),
            (    'Above the Break 3',               'FGA'),
            (    'Above the Break 3',            'FG_PCT'),
            (            'Backcourt',               'FGM'),
            (            'Backcourt',               'FGA'),
            (            'Backcourt',            'FG_PCT'),
            (             'Corner 3',               'FGM'),
            (             'Corner 3',               'FGA'),
            (             'Corner 3',            'FG_PCT')],
           names=['SHOT_CATEGORY', 'columns'])

In [33]:
# Flatten the MultiIndex columns
test_df.columns = [
    col[1] if col[0] == "" else f"{col[0]}_{col[1]}"
    for col in test_df.columns
]

print(test_df.columns.tolist())

[np.str_('PLAYER_ID'), np.str_('PLAYER_NAME'), np.str_('TEAM_ID'), np.str_('TEAM_ABBREVIATION'), np.str_('AGE'), np.str_('NICKNAME'), 'Restricted Area_FGM', 'Restricted Area_FGA', 'Restricted Area_FG_PCT', 'In The Paint (Non-RA)_FGM', 'In The Paint (Non-RA)_FGA', 'In The Paint (Non-RA)_FG_PCT', 'Mid-Range_FGM', 'Mid-Range_FGA', 'Mid-Range_FG_PCT', 'Left Corner 3_FGM', 'Left Corner 3_FGA', 'Left Corner 3_FG_PCT', 'Right Corner 3_FGM', 'Right Corner 3_FGA', 'Right Corner 3_FG_PCT', 'Above the Break 3_FGM', 'Above the Break 3_FGA', 'Above the Break 3_FG_PCT', 'Backcourt_FGM', 'Backcourt_FGA', 'Backcourt_FG_PCT', 'Corner 3_FGM', 'Corner 3_FGA', 'Corner 3_FG_PCT']

In [34]:
shot_zone_columns = [
    col for col in test_df.columns
    if "FGA" in col
]

print(shot_zone_columns)

['Restricted Area_FGA', 'In The Paint (Non-RA)_FGA', 'Mid-Range_FGA', 'Left Corner 3_FGA', 'Right Corner 3_FGA', 'Above the Break 3_FGA', 'Backcourt_FGA', 'Corner 3_FGA']

In [35]:
print(shot_zone_columns)

['Restricted Area_FGA', 'In The Paint (Non-RA)_FGA', 'Mid-Range_FGA', 'Left Corner 3_FGA', 'Right Corner 3_FGA', 'Above the Break 3_FGA', 'Backcourt_FGA', 'Corner 3_FGA']

In [36]:
# Shot-location columns used for the similarity model
shot_zone_fga = [
    "Restricted Area_FGA",
    "In The Paint (Non-RA)_FGA",
    "Mid-Range_FGA",
    "Corner 3_FGA",
    "Above the Break 3_FGA",
    "Backcourt_FGA"
]

# Filter to our 70-player candidate pool
candidate_shots = test_df[
    test_df["PLAYER_ID"].isin(candidate_pool["PLAYER_ID"])
].copy()

print("Candidate players:", candidate_shots["PLAYER_ID"].nunique())
print("Rows:", candidate_shots.shape)

Candidate players: 70
Rows: (70, 30)

In [37]:
# Total shots represented by the six non-overlapping zones
candidate_shots["TOTAL_ZONE_FGA"] = candidate_shots[shot_zone_fga].sum(axis=1)

# Convert each zone into a percentage of the player's shots
for col in shot_zone_fga:
    zone_name = col.replace("_FGA", "")
    candidate_shots[f"{zone_name}_FREQ"] = (
        candidate_shots[col] / candidate_shots["TOTAL_ZONE_FGA"] * 100
    )

print(
    candidate_shots[
        ["PLAYER_NAME"] +
        [col.replace("_FGA", "_FREQ") for col in shot_zone_fga]
    ].head(10).round(2)
)

        PLAYER_NAME  Restricted Area_FREQ  In The Paint (Non-RA)_FREQ  \
3      Aaron Gordon                 32.43                       15.32
21    Amen Thompson                 48.48                       29.55
27   Andrew Wiggins                 27.27                       19.83
28  Anfernee Simons                  9.24                       16.81
31  Anthony Edwards                 22.17                       16.75
37    Austin Reaves                 23.49                       27.52
39      Bam Adebayo                 24.84                       28.66
53     Bradley Beal                 18.75                       25.00
57   Brandon Ingram                 17.37                       22.75
58   Brandon Miller                 14.91                       23.60

    Mid-Range_FREQ  Corner 3_FREQ  Above the Break 3_FREQ  Backcourt_FREQ
3            12.61          11.71                   27.93             0.0
21           10.61           6.82                    4.55             0.0
27           12.40           9.92                   30.58             0.0
28           15.97           5.88                   52.10             0.0
31           19.21           4.43                   37.44             0.0
37            6.04           6.04                   36.91             0.0
39           11.46          11.46                   23.57             0.0
53           16.25           8.75                   31.25             0.0
57           32.34           7.19                   20.36             0.0
58           10.56           6.83                   44.10             0.0

In [38]:
shooting_tendency_columns = [
    "PLAYER_ID",
    "PLAYER_NAME",
    "Restricted Area_FREQ",
    "In The Paint (Non-RA)_FREQ",
    "Mid-Range_FREQ",
    "Corner 3_FREQ",
    "Above the Break 3_FREQ",
    "Backcourt_FREQ"
]

candidate_shot_profile = candidate_shots[shooting_tendency_columns].copy()

candidate_shot_profile.head(10).round(2)

,PLAYER_ID,PLAYER_NAME,Restricted Area_FREQ,In The Paint (Non-RA)_FREQ,Mid-Range_FREQ,Corner 3_FREQ,Above the Break 3_FREQ,Backcourt_FREQ
3,203932,Aaron Gordon,32.43,15.32,12.61,11.71,27.93,0.0
21,1641708,Amen Thompson,48.48,29.55,10.61,6.82,4.55,0.0
27,203952,Andrew Wiggins,27.27,19.83,12.40,9.92,30.58,0.0
28,1629014,Anfernee Simons,9.24,16.81,15.97,5.88,52.10,0.0
31,1630162,Anthony Edwards,22.17,16.75,19.21,4.43,37.44,0.0
37,1630559,Austin Reaves,23.49,27.52,6.04,6.04,36.91,0.0
39,1628389,Bam Adebayo,24.84,28.66,11.46,11.46,23.57,0.0
53,203078,Bradley Beal,18.75,25.00,16.25,8.75,31.25,0.0
57,1627742,Brandon Ingram,17.37,22.75,32.34,7.19,20.36,0.0
58,1641706,Brandon Miller,14.91,23.60,10.56,6.83,44.10,0.0

In [39]:
from pathlib import Path

output_path = Path("../data/processed/candidate_shot_profile_2025_26.csv")
output_path.parent.mkdir(parents=True, exist_ok=True)

candidate_shot_profile.to_csv(output_path, index=False)

print(f"Saved to: {output_path}")

Saved to: ..\data\processed\candidate_shot_profile_2025_26.csv

In [40]:
frequency_columns = [
    "Restricted Area_FREQ",
    "In The Paint (Non-RA)_FREQ",
    "Mid-Range_FREQ",
    "Corner 3_FREQ",
    "Above the Break 3_FREQ",
    "Backcourt_FREQ"
]

print(
    candidate_shot_profile[frequency_columns].sum(axis=1).head(10).round(2)
)

3     100.0
21    100.0
27    100.0
28    100.0
31    100.0
37    100.0
39    100.0
53    100.0
57    100.0
58    100.0
dtype: float64

In [42]:
from nba_api.stats.endpoints import leaguedashplayershotlocations

In [43]:
import pandas as pd
import time

kobe_shot_data = []

for season in df["SEASON_ID"]:
    try:
        season_shots = leaguedashplayershotlocations.LeagueDashPlayerShotLocations(
            season=season,
            season_type_all_star="Regular Season",
            measure_type_simple="Base",
            distance_range="By Zone",
            per_mode_detailed="PerGame"
        ).get_data_frames()[0]

        # Flatten MultiIndex columns
        season_shots.columns = [
            col[1] if col[0] == "" else f"{col[0]}_{col[1]}"
            for col in season_shots.columns
        ]

        # Keep Kobe only
        kobe_season = season_shots[
            season_shots["PLAYER_ID"] == 977
        ].copy()

        if not kobe_season.empty:
            kobe_season["SEASON_ID"] = season
            kobe_shot_data.append(kobe_season)
            print(season, "done")
        else:
            print(season, "Kobe not found")

        time.sleep(0.5)

    except Exception as e:
        print(season, "ERROR:", e)

print("Seasons collected:", len(kobe_shot_data))

1996-97 done
1997-98 done
1998-99 done
1999-00 done
2000-01 done
2001-02 done
2002-03 done
2003-04 done
2004-05 done
2005-06 done
2006-07 done
2007-08 done
2008-09 done
2009-10 done
2010-11 done
2011-12 done
2012-13 done
2013-14 done
2014-15 done
2015-16 done
Seasons collected: 20

In [46]:
# Bring games played from Kobe's original career dataset
kobe_shots = kobe_shots.merge(
    df[["SEASON_ID", "GP"]],
    on="SEASON_ID",
    how="left"
)

print(kobe_shots[["SEASON_ID", "GP"]].head())
print("Missing GP:", kobe_shots["GP"].isna().sum())

  SEASON_ID  GP
0   1996-97  71
1   1997-98  79
2   1998-99  50
3   1999-00  66
4   2000-01  68
Missing GP: 0

In [47]:
shot_zone_fga = [
    "Restricted Area_FGA",
    "In The Paint (Non-RA)_FGA",
    "Mid-Range_FGA",
    "Corner 3_FGA",
    "Above the Break 3_FGA",
    "Backcourt_FGA"
]

kobe_shot_profile = {
    "PLAYER_ID": 977,
    "PLAYER_NAME": "Kobe Bryant"
}

for zone in shot_zone_fga:
    total_attempts = (
        kobe_shots[zone] * kobe_shots["GP"]
    ).sum()

    kobe_shot_profile[
        zone.replace("_FGA", "_FREQ")
    ] = total_attempts

total_career_zone_fga = sum(
    value
    for key, value in kobe_shot_profile.items()
    if key.endswith("_FREQ")
)

for key in list(kobe_shot_profile.keys()):
    if key.endswith("_FREQ"):
        kobe_shot_profile[key] = (
            kobe_shot_profile[key]
            / total_career_zone_fga
            * 100
        )

kobe_shot_profile_df = pd.DataFrame([kobe_shot_profile])

kobe_shot_profile_df.round(2)

,PLAYER_ID,PLAYER_NAME,Restricted Area_FREQ,In The Paint (Non-RA)_FREQ,Mid-Range_FREQ,Corner 3_FREQ,Above the Break 3_FREQ,Backcourt_FREQ
0,977,Kobe Bryant,23.19,14.49,40.88,2.23,18.48,0.72

In [48]:
frequency_columns = [
    "Restricted Area_FREQ",
    "In The Paint (Non-RA)_FREQ",
    "Mid-Range_FREQ",
    "Corner 3_FREQ",
    "Above the Break 3_FREQ",
    "Backcourt_FREQ"
]

print(
    kobe_shot_profile_df[frequency_columns].sum(axis=1).round(2)
)

0    100.0
dtype: float64

In [49]:
output_path = Path("../data/processed/kobe_shot_profile_career.csv")

kobe_shot_profile_df.to_csv(output_path, index=False)

print(f"Saved to: {output_path}")

Saved to: ..\data\processed\kobe_shot_profile_career.csv

In [50]:
category_metrics = {
    "Stature": [
        "height",
        "weight",
        "wingspan"
    ],

    "Shooting Tendencies": [
        "Restricted Area_FREQ",
        "In The Paint (Non-RA)_FREQ",
        "Mid-Range_FREQ",
        "Corner 3_FREQ",
        "Above the Break 3_FREQ",
        "Backcourt_FREQ"
    ],

    "Portability": [
        "specialized portability rating"
    ],

    "Passing": [
        "APG",
        "AST_PCT",
        "AST_TO"
    ],

    "Usage & Creation": [
        "USG_PCT",
        "PPG",
        "FGA"
    ],

    "Defense": [
        "SPG",
        "BPG",
        "DEF_RATING"
    ],

    "Athleticism": [
        "vertical leap"
    ],

    "Dominance": [
        "NET_RATING",
        "PIE"
    ],

    "Shooting Ability": [
        "FG_PCT",
        "FG3_PCT",
        "FT_PCT",
        "TS_PCT",
        "EFG_PCT"
    ],

    "Play Style": [
        "ISO",
        "PNR_BALL_HANDLER",
        "PNR_ROLL_MAN",
        "POST_UP",
        "SPOT_UP",
        "CUT",
        "HANDOFF",
        "OFF_SCREEN"
    ]
}

for category, metrics in category_metrics.items():
    print(f"\n{category}:")
    for metric in metrics:
        print(" -", metric)

Stature:
 - height
 - weight
 - wingspan

Shooting Tendencies:
 - Restricted Area_FREQ
 - In The Paint (Non-RA)_FREQ
 - Mid-Range_FREQ
 - Corner 3_FREQ
 - Above the Break 3_FREQ
 - Backcourt_FREQ

Portability:
 - specialized portability rating

Passing:
 - APG
 - AST_PCT
 - AST_TO

Usage & Creation:
 - USG_PCT
 - PPG
 - FGA

Defense:
 - SPG
 - BPG
 - DEF_RATING

Athleticism:
 - vertical leap

Dominance:
 - NET_RATING
 - PIE

Shooting Ability:
 - FG_PCT
 - FG3_PCT
 - FT_PCT
 - TS_PCT
 - EFG_PCT

Play Style:
 - ISO
 - PNR_BALL_HANDLER
 - PNR_ROLL_MAN
 - POST_UP
 - SPOT_UP
 - CUT
 - HANDOFF
 - OFF_SCREEN

In [51]:
print("Candidate shot profile:", candidate_shot_profile.shape)
print("Kobe shot profile:", kobe_shot_profile_df.shape)

Candidate shot profile: (70, 8)
Kobe shot profile: (1, 8)